"""Initial schema

Revision ID: 2ee9e87ede55
Revises: 
Create Date: 2025-11-19 00:25:55.126077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ee9e87ede55'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('yaml_content', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_domain'), 'contracts', ['domain'], unique=False)
    op.create_index(op.f('ix_contracts_is_active'), 'contracts', ['is_active'], unique=False)
    op.create_index(op.f('ix_contracts_name'), 'contracts', ['name'], unique=True)
    op.create_table('contract_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('yaml_content', sa.Text(), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=True),
    sa.Column('change_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_versions_contract_id'), 'contract_versions', ['contract_id'], unique=False)
    op.create_index('ix_contract_versions_contract_version', 'contract_versions', ['contract_id', 'version'], unique=True)
    op.create_index('ix_contract_versions_created_at', 'contract_versions', ['created_at'], unique=False)
    op.create_table('quality_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('total_validations', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('pass_rate', sa.Float(), nullable=True),
    sa.Column('avg_execution_time_ms', sa.Float(), nullable=True),
    sa.Column('top_errors', sa.JSON(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quality_metrics_contract_date', 'quality_metrics', ['contract_id', 'metric_date'], unique=True)
    op.create_index(op.f('ix_quality_metrics_contract_id'), 'quality_metrics', ['contract_id'], unique=False)
    op.create_index('ix_quality_metrics_date', 'quality_metrics', ['metric_date'], unique=False)
    op.create_table('validation_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_snapshot', sa.JSON(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('execution_time_ms', sa.Float(), nullable=False),
    sa.Column('validated_at', sa.DateTime(), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_batch_id'), 'validation_results', ['batch_id'], unique=False)
    op.create_index('ix_validation_results_contract_date', 'validation_results', ['contract_id', 'validated_at'], unique=False)
    op.create_index(op.f('ix_validation_results_contract_id'), 'validation_results', ['contract_id'], unique=False)
    op.create_index(op.f('ix_validation_results_status'), 'validation_results', ['status'], unique=False)
    op.create_index(op.f('ix_validation_results_validated_at'), 'validation_results', ['validated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_results_validated_at'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_status'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_contract_id'), table_name='validation_results')
    op.drop_index('ix_validation_results_contract_date', table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_batch_id'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index('ix_quality_metrics_date', table_name='quality_metrics')
    op.drop_index(op.f('ix_quality_metrics_contract_id'), table_name='quality_metrics')
    op.drop_index('ix_quality_metrics_contract_date', table_name='quality_metrics')
    op.drop_table('quality_metrics')
    op.drop_index('ix_contract_versions_created_at', table_name='contract_versions')
    op.drop_index('ix_contract_versions_contract_version', table_name='contract_versions')
    op.drop_index(op.f('ix_contract_versions_contract_id'), table_name='contract_versions')
    op.drop_table('contract_versions')
    op.drop_index(op.f('ix_contracts_name'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_is_active'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_domain'), table_name='contracts')
    op.drop_table('contracts')
    # ### end Alembic commands ###
